# Generated by Django 4.2.7 on 2024-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobnyak', '0002_fill_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.SmallIntegerField(choices=[(0, 'Дома, коттеджи'), (1, 'Модульные строения')], default=1),
            preserve_default=False,
        ),
    ]
