# Generated by Django 4.2.7 on 2024-03-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osobnyak', '0003_category_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['page', 'ordering']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__page', 'category__ordering', 'ordering']},
        ),
    ]
